### ISSUE TITLE
Obtained access token but no pixels are being placed

### ISSUE THREAD

**Issue by Conchuckter** [ForsenPlace/Script#3]
After the token and orders are obtained no pixels are placed.

Browser: Firefox; Using: Violentmonkey;

**Comment by Conchuckter** [comment]
I think it could be something to do with violent monkey, closing.

**Comment by ForsenPlace** [comment]
I just fixed an issue with pixels placed on the expanded areas, didn't catch it in time because we're focused on the original canvas.

Please check if it's related

**Comment by i0Smile** [comment]
This is not in the spirit of the place

**Comment by Conchuckter** [comment]
> This is not in the spirit of the place

Well the code is cool and, everyone is using them anyway. So even if they were to stop there would still be a large amount of people continuing to do so.

**Comment by Conchuckter** [comment]
> I just fixed an issue with pixels placed on the expanded areas, didn't catch it in time because we're focused on the original canvas.
> 
> Please check if it's related

I'll check in a bit but it'll be like 1 hour before place is rumoured to close.

**Comment by Jorkoh** [comment]
Yep, a bit too late. It was fun while it lasted!

**Comment by ForsenPlace** [comment]
Hope you guys finished r/place in a good spot. Closing this since it's over
